//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.GroupClasses = new HashSet<GroupClasses>();
            this.PersonalTrainings = new HashSet<PersonalTrainings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int Capacity { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<bool> HasEquipment { get; set; }
        public string EquipmentList { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<GroupClasses> GroupClasses { get; set; }
        public virtual ICollection<PersonalTrainings> PersonalTrainings { get; set; }
    }
}
