//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.ClientMemberships = new HashSet<ClientMemberships>();
            this.GroupClassBookings = new HashSet<GroupClassBookings>();
            this.Payments = new HashSet<Payments>();
            this.PersonalTrainings = new HashSet<PersonalTrainings>();
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string HealthIssues { get; set; }
        public string EmergencyContact { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public string BlockReason { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<ClientMemberships> ClientMemberships { get; set; }
        public virtual ICollection<GroupClassBookings> GroupClassBookings { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<PersonalTrainings> PersonalTrainings { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
