//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMemberships
    {
        public ClientMemberships()
        {
            this.MembershipFreezes = new HashSet<MembershipFreezes>();
            this.Payments = new HashSet<Payments>();
            this.PersonalTrainings = new HashSet<PersonalTrainings>();
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int MembershipTypeId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> RemainingVisits { get; set; }
        public string Status { get; set; }
        public Nullable<int> FrozenDays { get; set; }
        public Nullable<System.DateTime> FrozenUntil { get; set; }
        public int SoldBy { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual MembershipTypes MembershipTypes { get; set; }
        public virtual ICollection<MembershipFreezes> MembershipFreezes { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<PersonalTrainings> PersonalTrainings { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
