//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.ClientMemberships = new HashSet<ClientMemberships>();
            this.GroupClassBookings = new HashSet<GroupClassBookings>();
            this.MembershipFreezes = new HashSet<MembershipFreezes>();
            this.Payments = new HashSet<Payments>();
            this.Trainers = new HashSet<Trainers>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PassportData { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<ClientMemberships> ClientMemberships { get; set; }
        public virtual ICollection<GroupClassBookings> GroupClassBookings { get; set; }
        public virtual ICollection<MembershipFreezes> MembershipFreezes { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<Trainers> Trainers { get; set; }
    }
}
