//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClasses
    {
        public GroupClasses()
        {
            this.GroupClassSchedule = new HashSet<GroupClassSchedule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ClassId { get; set; }
        public int TrainerId { get; set; }
        public int Duration { get; set; }
        public string Difficulty { get; set; }
        public int MaxParticipants { get; set; }
        public Nullable<int> MinParticipants { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ColorCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Trainers Trainers { get; set; }
        public virtual ICollection<GroupClassSchedule> GroupClassSchedule { get; set; }
    }
}
