//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClassSchedule
    {
        public GroupClassSchedule()
        {
            this.GroupClassBookings = new HashSet<GroupClassBookings>();
        }
    
        public int Id { get; set; }
        public int GroupClassId { get; set; }
        public int DayOfWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<GroupClassBookings> GroupClassBookings { get; set; }
        public virtual GroupClasses GroupClasses { get; set; }
    }
}
