//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClassBookings
    {
        public GroupClassBookings()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public int GroupClassScheduleId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual GroupClassSchedule GroupClassSchedule { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
