//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipFreezes
    {
        public int Id { get; set; }
        public int ClientMembershipId { get; set; }
        public System.DateTime FreezeStartDate { get; set; }
        public System.DateTime FreezeEndDate { get; set; }
        public string Reason { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ClientMemberships ClientMemberships { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
