//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTypes
    {
        public MembershipTypes()
        {
            this.ClientMemberships = new HashSet<ClientMemberships>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> DurationDays { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public string TrainerType { get; set; }
        public Nullable<bool> IsPersonalAllowed { get; set; }
        public Nullable<bool> IsGroupAllowed { get; set; }
        public Nullable<bool> HasPool { get; set; }
        public Nullable<bool> HasGym { get; set; }
        public Nullable<int> FreezeDays { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<ClientMemberships> ClientMemberships { get; set; }
    }
}
