//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnesClubDbEntities : DbContext
    {
        public FitnesClubDbEntities()
            : base("name=FitnesClubDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Classes> Classes { get; set; }
        public DbSet<ClientMemberships> ClientMemberships { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<GroupClassBookings> GroupClassBookings { get; set; }
        public DbSet<GroupClasses> GroupClasses { get; set; }
        public DbSet<GroupClassSchedule> GroupClassSchedule { get; set; }
        public DbSet<MembershipFreezes> MembershipFreezes { get; set; }
        public DbSet<MembershipTypes> MembershipTypes { get; set; }
        public DbSet<Payments> Payments { get; set; }
        public DbSet<PersonalTrainings> PersonalTrainings { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Trainers> Trainers { get; set; }
        public DbSet<TrainerSchedule> TrainerSchedule { get; set; }
        public DbSet<Visits> Visits { get; set; }
    }
}
