//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public Payments()
        {
            this.PersonalTrainings = new HashSet<PersonalTrainings>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientMembershipId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public string TransactionId { get; set; }
        public int ReceivedBy { get; set; }
        public string Description { get; set; }
    
        public virtual ClientMemberships ClientMemberships { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<PersonalTrainings> PersonalTrainings { get; set; }
    }
}
