//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalTrainings
    {
        public PersonalTrainings()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int TrainerId { get; set; }
        public int ClassId { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> ClientMembershipId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual ClientMemberships ClientMemberships { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual Trainers Trainers { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
