//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSchedule
    {
        public int Id { get; set; }
        public int TrainerId { get; set; }
        public int DayOfWeek { get; set; }
        public System.TimeSpan WorkStartTime { get; set; }
        public System.TimeSpan WorkEndTime { get; set; }
        public Nullable<bool> IsWorkingDay { get; set; }
        public Nullable<System.TimeSpan> BreakStartTime { get; set; }
        public Nullable<System.TimeSpan> BreakEndTime { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    
        public virtual Trainers Trainers { get; set; }
    }
}
