//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainers
    {
        public Trainers()
        {
            this.GroupClasses = new HashSet<GroupClasses>();
            this.PersonalTrainings = new HashSet<PersonalTrainings>();
            this.TrainerSchedule = new HashSet<TrainerSchedule>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Specialization { get; set; }
        public string TrainerType { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Bio { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<bool> IsAvailableForPersonal { get; set; }
        public Nullable<int> MaxPersonalClients { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<GroupClasses> GroupClasses { get; set; }
        public virtual ICollection<PersonalTrainings> PersonalTrainings { get; set; }
        public virtual ICollection<TrainerSchedule> TrainerSchedule { get; set; }
    }
}
