//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ClientMembershipId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string VisitType { get; set; }
        public Nullable<int> GroupClassBookingId { get; set; }
        public Nullable<int> PersonalTrainingId { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual ClientMemberships ClientMemberships { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual GroupClassBookings GroupClassBookings { get; set; }
        public virtual PersonalTrainings PersonalTrainings { get; set; }
    }
}
